name = "GSRTVerification"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["GSRTVerification"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
# This is not a Mathlib file, so no Mathlib copyright header is expected.
weak.linter.style.header = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.35.0-rc2"

[[lean_lib]]
name = "GSRTVerification"
